#!/bin/bash
USERNAME=/Users/kalaishelvan/Desktop/scripting/username
KEY= /Users/kalaishelvan/Downloads/folder/NewKey.pem
HOSTS=/Users/kalaishelvan/Downloads/folder/hostname
for HOSTNAME in ${HOSTS} ; do
ssh -i ${KEY} ${USERNAME} ${HOSTS}
done

